import { useState } from 'react'
import { Canvas } from '@react-three/fiber'
import { OrbitControls, ContactShadows} from '@react-three/drei'
import * as THREE from 'three'
import './App.css'

// Custom Components
import DraggableItem from './draggableItem'
// Make sure to match these imports with the exact names generated by gltfjsx
import { Sofa } from './Sofa'   
import { Table } from './Table'
import { Bookcase } from './Bookcase'
import { Tv_stand } from './Tv_stand'
import { Bergere } from './Bergere'
import { Wardrobe } from './Wardrobe'
import { Fridge } from './Fridge'
import { Bathroomset } from './Bathroomset'

export default function App() {
  // Room dimensions state (in meters)
  const [roomWidth, setRoomWidth] = useState(4)
  const [roomDepth, setRoomDepth] = useState(5)
  const [roomHeight, setRoomHeight] = useState(2.8)

  // Array state to keep track of added furniture items in the scene
  const [furnitureList, setFurnitureList] = useState([])

  /**
   * Adds a new furniture item to the scene list.
   * @param {string} type - The type of furniture to add (e.g., 'sofa', 'table', 'bookcase')
   */
  const addFurniture = (type) => {
    // Generate a unique ID using Date.now() for React keys
    const newItem = { type: type, id: Date.now() }
    setFurnitureList([...furnitureList, newItem])
  }

  return (
    <div style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column' }}>
      
      {/* --- UI LAYER (TOP MENU) --- */}
      <div style={{ padding: '20px', backgroundColor: '#2c3e50', color: 'white', display: 'flex', gap: '20px', alignItems: 'center', flexWrap: 'wrap' }}>
        <h3>🛠️ Room Planner</h3>
        
        {/* Room Dimension Inputs */}
        <label>
          Width (X): 
          <input 
            type="number" 
            value={roomWidth} 
            onChange={(e) => setRoomWidth(e.target.value === '' ? '' : Number(e.target.value))} 
            style={{ width: '50px', marginLeft: '5px' }} 
          /> m
        </label>
        <label>
          Depth (Z): 
          <input 
            type="number" 
            value={roomDepth} 
            onChange={(e) => setRoomDepth(e.target.value === '' ? '' : Number(e.target.value))} 
            style={{ width: '50px', marginLeft: '5px' }} 
          /> m
        </label>
        <label>
          Height (Y): 
          <input 
            type="number" 
            step="0.1"
            value={roomHeight} 
            onChange={(e) => setRoomHeight(e.target.value === '' ? '' : Number(e.target.value))} 
            style={{ width: '50px', marginLeft: '5px' }} 
          /> m
        </label>
        
        {/* Furniture Action Buttons */}
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '10px' }}>
          <button onClick={() => addFurniture('sofa')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Sofa</button>
          <button onClick={() => addFurniture('table')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Table</button>
          <button onClick={() => addFurniture('bookcase')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Bookcase</button>
          <button onClick={() => addFurniture('tv_stand')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Tv_stand</button>
          <button onClick={() => addFurniture('bergere')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Bergere</button>
          <button onClick={() => addFurniture('wardrobe')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Wardrobe</button>
          <button onClick={() => addFurniture('fridge')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Fridge</button>
          <button onClick={() => addFurniture('bathroomset')} style={{ padding: '8px 16px', cursor: 'pointer' }}>+ Add Bathroomset</button>
        </div>
      </div>

      {/* --- 3D SCENE LAYER --- */}
      <div style={{ flex: 1, backgroundColor: '#1a1a1a' }}>
        <Canvas camera={{ position: [0, 5, 10], fov: 50 }}>
          
          {/* Scene Lighting */}
          <ambientLight intensity={0.6} />
          <directionalLight position={[10, 10, 5]} intensity={1} />
          
          {/* Static Environment (Room Walls and Floor) */}
          <group>
            {/* Floor */}
            <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, 0, 0]}>
              <planeGeometry args={[roomWidth, roomDepth]} />
              <meshStandardMaterial color="#b0bec5" side={THREE.DoubleSide} />
            </mesh>
            {/* Back Wall */}
            <mesh position={[0, roomHeight / 2, -roomDepth / 2]}>
              <planeGeometry args={[roomWidth, roomHeight]} />
              <meshStandardMaterial color="#e0e0e0" side={THREE.DoubleSide} transparent={true} opacity={0.3} />
            </mesh>
            {/* Front Wall */}
            <mesh position={[0, roomHeight / 2, roomDepth / 2]}>
              <planeGeometry args={[roomWidth, roomHeight]} />
              <meshStandardMaterial color="#e0e0e0" side={THREE.DoubleSide} transparent={true} opacity={0.3} />
            </mesh>
            {/* Left Wall */}
            <mesh rotation={[0, Math.PI / 2, 0]} position={[-roomWidth / 2, roomHeight / 2, 0]}>
              <planeGeometry args={[roomDepth, roomHeight]} />
              <meshStandardMaterial color="#e0e0e0" side={THREE.DoubleSide} transparent={true} opacity={0.3} />
            </mesh>
            {/* Right Wall */}
            <mesh rotation={[0, Math.PI / 2, 0]} position={[roomWidth / 2, roomHeight / 2, 0]}>
              <planeGeometry args={[roomDepth, roomHeight]} />
              <meshStandardMaterial color="#e0e0e0" side={THREE.DoubleSide} transparent={true} opacity={0.3} />
            </mesh>
          </group>

          {/* Reference Grid */}
          <gridHelper args={[50, 50, '#000000', '#333333']} position={[0, 0.01, 0]} />

          {/* Dynamic Furniture Rendering */}
          {furnitureList.map((item) => (
            <DraggableItem key={item.id}>
              {item.type === 'sofa' && <Sofa scale={[1.3, 1.5, 1.2]} />}

              {item.type === 'table' && <Table scale={[0.28, 0.27, 0.4]} />}

              {item.type === 'bookcase' && <Bookcase scale={[1.5, 0.9, 1]} />}

              {item.type === 'tv_stand' && <Tv_stand scale={[1.5, 0.7, 1]} />}

              {item.type === 'bergere' && <Bergere scale={[2, 1.755, 1.5]} />}

              {item.type === 'wardrobe' && <Wardrobe scale={[0.5, 0.48, 0.5]} />}

              {item.type === 'fridge' && <Fridge scale={[0.18, 0.18, 0.2]} />}

              {item.type === 'bathroomset' && <Bathroomset scale={[1, 0.8, 1]} />}
            </DraggableItem>
          ))}

          {/* Camera Controls */}
          <OrbitControls makeDefault />
        </Canvas>
      </div>
    </div>
  )
}