/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bathroomset.glb 
Author: General of Thailand (https://sketchfab.com/Melonpolygons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bathroom-furniture-set-game-ready-0aabe78df5be407ea48e7ed70afd16a0
Title: Bathroom Furniture Set - Game Ready
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bathroomset(props) {
  const { nodes, materials } = useGLTF('/bathroomset.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[125, 125, 200]}>
          <mesh geometry={nodes.Plane001_Material_3_0.geometry} material={materials.Material_3} />
          <mesh geometry={nodes.Plane001_Material_1_0.geometry} material={materials.Material_1} />
          <mesh geometry={nodes.Plane001_Material_2_0.geometry} material={materials.Material_2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bathroomset.glb')
