/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bergere.glb 
Author: CEOHive (https://sketchfab.com/ceohive)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylish-luxury-cushioned-couch-relax-sofa-00cc50baac2b4a639c6c080877e3d04a
Title: Stylish & Luxury Cushioned Couch Relax  Sofa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bergere(props) {
  const { nodes, materials } = useGLTF('/bergere.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/bergere.glb')
