/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/bookcase.glb 
Author: Coreliss (https://sketchfab.com/Coreliss)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/stylized-bookcase-2k-pbr-unreal-c5072f6ced444c9e9dec252ad5dd1aeb
Title: Stylized BOOKCASE 2k PBR, UNREAL
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Bookcase(props) {
  const { nodes, materials } = useGLTF('/bookcase.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Bookcase_1_Decor_0.geometry} material={materials.Decor} position={[-83.757, 40.36, 20.405]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bookcase_2_Decor_0.geometry} material={materials.Decor} position={[-84.461, 47.363, 20.515]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books1_Decor_0.geometry} material={materials.Decor} position={[-83.603, 92.454, 61.582]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books10_Decor_0.geometry} material={materials.Decor} position={[-83.603, 37.754, 61.692]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books11_Decor_0.geometry} material={materials.Decor} position={[-83.603, 37.751, 20.682]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books12_Decor_0.geometry} material={materials.Decor} position={[-85.099, 2.102, -7.249]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books13_Decor_0.geometry} material={materials.Decor} position={[-84.542, 7.994, 15.917]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books14_Decor_0.geometry} material={materials.Decor} position={[-83.603, 10.351, 61.639]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books15_Decor_0.geometry} material={materials.Decor} position={[-84.542, 7.914, 40.793]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books16_Decor_0.geometry} material={materials.Decor} position={[-84.542, 35.336, 41.191]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books17_Decor_0.geometry} material={materials.Decor} position={[-83.603, 37.712, -20.776]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books18_Decor_0.geometry} material={materials.Decor} position={[-84.542, 35.341, 0.07]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books2_Decor_0.geometry} material={materials.Decor} position={[-84.776, 88.794, 11.434]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books3_Decor_0.geometry} material={materials.Decor} position={[-84.542, 90.06, 40.736]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books4_Decor_0.geometry} material={materials.Decor} position={[-83.603, 119.795, -20.744]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books5_Decor_0.geometry} material={materials.Decor} position={[-85.099, 110.536, 25.067]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books6_Decor_0.geometry} material={materials.Decor} position={[-83.603, 65.089, 20.691]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books7_Decor_0.geometry} material={materials.Decor} position={[-83.603, 65.089, -20.733]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books8_Decor_0.geometry} material={materials.Decor} position={[-84.542, 62.668, -0.245]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Books9_Decor_0.geometry} material={materials.Decor} position={[-83.603, 58.867, 55.316]} rotation={[Math.PI, 0, 0]} scale={100} />
        <mesh geometry={nodes.Box001_Decor_0.geometry} material={materials.Decor} position={[-80.293, -30.309, 59.353]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Box002_Decor_0.geometry} material={materials.Decor} position={[-65.984, -31.78, 33.918]} rotation={[-Math.PI / 2, 0.32, 0.689]} scale={100} />
        <mesh geometry={nodes.Colb10_Decor_0.geometry} material={materials.Decor} position={[-85.135, 52.138, 46.892]} rotation={[0.037, 0.081, 0.188]} scale={100} />
        <mesh geometry={nodes.Colb4_Decor_0.geometry} material={materials.Decor} position={[-83.805, 60.566, 38.408]} rotation={[-Math.PI / 2, 0, 0]} scale={143.306} />
        <mesh geometry={nodes.Colb5_Decor_0.geometry} material={materials.Decor} position={[-87.232, 57.583, 34.622]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Colb6_Decor_0.geometry} material={materials.Decor} position={[-85.698, 111.125, 5.221]} rotation={[3.134, -0.535, -0.408]} scale={100} />
        <mesh geometry={nodes.Colb7_Decor_0.geometry} material={materials.Decor} position={[-85.514, 117.363, 62.923]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Colb8_Decor_0.geometry} material={materials.Decor} position={[-85.446, 5.992, -23.596]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Colb9_Decor_0.geometry} material={materials.Decor} position={[-85.543, 120.663, 50.183]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Headdress001_Decor_0.geometry} material={materials.Decor} position={[-79.643, -35.017, -14.538]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/bookcase.glb')
