/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fridge.glb 
Author: Ishxxn (https://sketchfab.com/1shxxn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fridge-modern-furniture-game-ready-c908eae9b0bd49a3a6f7ecbf9526b54a
Title: Fridge - Modern Furniture (Game-ready)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Fridge(props) {
  const { nodes, materials } = useGLTF('/fridge.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Fridge_Fridge_atlas_0.geometry} material={materials.Fridge_atlas} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-223.931, 223.931, 496.004]} />
      </group>
    </group>
  )
}

useGLTF.preload('/fridge.glb')
