/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/sofa.glb 
Author: leoxx300 (https://sketchfab.com/leoxx300)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-sofa-305e5b68c7bf409ba4bc6c56d242f8fc
Title: low poly sofa
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Sofa(props) {
  const { nodes, materials } = useGLTF('/sofa.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.sofa_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/sofa.glb')
