/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/table.glb 
Author: Bob (https://sketchfab.com/mabeluke1234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylised-table-c555238797dc4ac887ffffe665c20c6a
Title: Stylised Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Table(props) {
  const { nodes, materials } = useGLTF('/table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0.006, -0.658, 0.002]} />
    </group>
  )
}

useGLTF.preload('/table.glb')
