/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/tv_stand.glb 
Author: SaretiX (https://sketchfab.com/SaretiX)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/modern-slatted-wooden-tv-stand-f0e5b2882c864a4b9aec1266115a13a4
Title: Modern Slatted Wooden TV Stand
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Tv_stand(props) {
  const { nodes, materials } = useGLTF('/tv_stand.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.SlattedTVStand_SlattedTVStand_0.geometry} material={materials.SlattedTVStand} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/tv_stand.glb')
