/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/wardrobe.glb 
Author: ArchVibe 3D (https://sketchfab.com/super-valentin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-scandinavian-style-wardrobe-d8f7d929a92440e185f782855c034321
Title: Modern Scandinavian style wardrobe
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Wardrobe(props) {
  const { nodes, materials } = useGLTF('/wardrobe.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[0.5, 2, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/wardrobe.glb')
